const linuxCommandsList = [
  {
    subheading: "File and Directory Operations(linux):",
    commands: ["ls", "pwd", "cd", "mkdir", "touch", "rm", "cp", "mv", "find"],
    searchKeywords: [
      "Linux",
      "linux files",
      "linux directories",
      "monving and renaming a directory",
      "find a directory in linux",
      "list directories",
      "current directory",
      "remove a directory",
      "finding a directory",
    ],
  },
  {
    subheading: "Text Editing and Viewing(linux):",
    commands: ["cat", "nano", "vim", "grep", "less", "head", "tail", "wc"],
    searchKeywords: ["Linux", "linux text viewing", "linux text editing"],
  },
  {
    subheading: "File Permissions(linux):",
    commands: ["chmod", "chown", "chgrp"],
    searchKeywords: ["Linux", "linux file permissions", "linux permissions"],
  },
  {
    subheading: "Processes and System Information(linux):",
    commands: ["ps", "top", "kill", "free", "df", "du", "uname"],
    searchKeywords: ["Linux", "System information", "linux processes "],
  },
  {
    subheading: "Package Management(linux):",
    commands: ["apt-get", "yum", "dnf"],
    searchKeywords: [
      "Linux",
      "package management  linux",
      "linux package management",
    ],
  },
  {
    subheading: "Networking(linux):",
    commands: ["ping", "ifconfig", "ip", "netstat", "ssh", "scp", "curl"],
    searchKeywords: ["Linux", "networking  linux", "linux networking"],
  },
  {
    subheading: "System Control(linux):",
    commands: [
      "shutdown",
      "reboot",
      "poweroff",
      "sudo",
      "su",
      "useradd",
      "usermod",
      "passwd",
    ],
    searchKeywords: ["Linux", "linux system control", "system linux"],
  },
  {
    subheading: "File Compression and Archiving(linux):",
    commands: ["tar", "gzip", "gunzip", "zip", "unzip", "rar", "unrar"],
    searchKeywords: ["Linux", "file compression linux", "archiving linux"],
  },
  {
    subheading: "Disk Management(linux):",
    commands: ["fdisk", "df", "du", "mkfs", "mount", "umount"],
    searchKeywords: ["Linux", "disk management linux", "linux disk management"],
  },
  {
    subheading: "Network Utilities(linux):",
    commands: [
      "ping",
      "nslookup",
      "traceroute",
      "netstat",
      "nc",
      "telnet",
      "ssh",
      "scp",
      "ftp",
      "wget",
      "curl",
      "nmap",
    ],
    searchKeywords: [
      "Linux",
      "linux networking utilities",
      "networking utilities linux",
    ],
  },
  {
    subheading: "User and Group Management(linux):",
    commands: [
      "useradd",
      "userdel",
      "passwd",
      "usermod",
      "groupadd",
      "groupdel",
      "groupmod",
      "id",
      "whoami",
      "su",
      "sudo",
    ],
    searchKeywords: [
      "Linux",
      "user management linux",
      "linux user management",
      "group management linux",
    ],
  },
  {
    subheading: "Process Monitoring and Management(linux):",
    commands: [
      "ps",
      "top",
      "htop",
      "kill",
      "pkill",
      "pgrep",
      "jobs",
      "bg",
      "fg",
      "nohup",
      "nice",
    ],
    searchKeywords: [
      "Linux",
      "linux process monitoring ",
      "process management linux",
    ],
  },
  {
    subheading: "System Information(linux):",
    commands: [
      "uname",
      "uptime",
      "who",
      "w",
      "last",
      "df",
      "free",
      "lshw",
      "lsblk",
      "lscpu",
    ],
    searchKeywords: ["Linux", "Information linux", "linux system info"],
  },
  {
    subheading: "Text Processing(linux):",
    commands: ["grep", "sed", "awk", "cut", "sort", "uniq", "head", "tail"],
    searchKeywords: ["Linux", "text process", "linux text processing"],
  },
  {
    subheading: "Miscellaneous(linux):",
    commands: [
      "date",
      "cal",
      "clear",
      "history",
      "echo",
      "which",
      "whereis",
      "locate",
      "man",
    ],
    searchKeywords: ["Linux", "miscellaneous linux"],
  },
];

export default linuxCommandsList;
